/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8B1MrHDuTXW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function search-barre() {
  return (
    <div className="flex w-full max-w-md items-center space-x-2">
      <div className="flex-1">
        <Select>
          <SelectTrigger className="w-full">
            <SelectValue placeholder="Choisir une langue" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="fr">Français</SelectItem>
            <SelectItem value="en">Anglais</SelectItem>
            <SelectItem value="es">Espagnol</SelectItem>
            <SelectItem value="de">Allemand</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <div className="flex-1">
        <Input type="text" placeholder="Région" />
      </div>
      <Button type="submit">Rechercher</Button>
    </div>
  )
}
